version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-PyQt5:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: PyQt5
      - run:
          command: pip install numpy PyQt5 nose
          name: Install Dependencies (PyQt5)
      - python/save-cache
      - run:
          command: nosetests
          environment:
            QT_API: pyqt5
          name: Test (PyQt5)
  
  test-PyQt4:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: PyQt4
      - run:
          command: pip install numpy PyQt4 nose
          name: Install Dependencies (PyQt4)
      - python/save-cache
      - run:
          command: nosetests
          environment:
            QT_API: pyqt
          name: Test (PyQt4)
  
  test-PySide2:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: PySide2
      - run:
          command: pip install numpy PySide2 nose
          name: Install Dependencies (PySide2)
      - python/save-cache
      - run:
          command: nosetests
          environment:
            QT_API: pyside2
          name: Test (PySide2)
  
workflows:
  main:
    jobs:
      - test-PyQt5
      - test-PyQt4
      - test-PySide2
