version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-PyQt5:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: QT_API=pyqt5 nosetests
          environment:
            QT_API: pyqt5
          name: Test

workflows:
  main:
    jobs:
      - test-PyQt5
